CC=vc
CFLAGS=-lamiga -lauto +aos68k -INDK:Include/include_h -Iinclude -c99 -IVBCC:targets/m68k-amigaos/include
OBJS=main.o utility.o usage.o list.o

all: setcmd test stub

setcmd: $(OBJS)
	$(CC) -o setcmd $(OBJS) $(CFLAGS)

stub: stub.o utility.o
	$(CC) -o stub stub.o utility.o $(CFLAGS)

test: test.o utility.o
	$(CC) -o test test.o utility.o $(CFLAGS)

%.o : %.c
	$(CC) -c -o $@ $< $(CFLAGS) 

clean:
	rm *.o test setcmd

debug: CFLAGS += -DDEBUG
debug: test
debug: setcmd
debug: stub
