CC=vc
CFLAGS=-lamiga -lauto +aos68k -INDK:Include/include_h -Iinclude -c99 -IVBCC:targets/m68k-amigaos/include
OBJS=main.o utility.o usage.o init_os3.o list_os3.o add_cmd.o add_version.o delete_version.o delete_cmd.o set_version.o show_os3.o

all: setcmd stub

setcmd: $(OBJS)
	$(CC) -o setcmd $(OBJS) $(CFLAGS)

stub: stub.o utility.o
	$(CC) -o stub stub.o utility.o $(CFLAGS)

test: test.o utility.o
	$(CC) -o test test.o utility.o $(CFLAGS)

%.o : %.c
	$(CC) -c -o $@ $< $(CFLAGS) 

clean:
	rm *.o setcmd stub

debug: CFLAGS += -DDEBUG
debug: setcmd
debug: stub
