---
kind: pipeline
name: build setcmd 68k
type: kubernetes

trigger:
  branch:
  - 68k
  event:
  - custom
  - push

steps:
- name: copy files
  image: busybox:latest
  volumes:
  - name: code
    path: /opt/code
  commands:
  - cp -r src.68k/* /opt/code/

- name: build binary
  image: walkero/docker4amigavbcc:latest-m68k-amd64
  volumes:
  - name: code
    path: /opt/code
  commands:
  - cd /opt/code
  - make -f makefile.docker

- name: create release artifact
  image: busybox
  volumes:
  - name: code
    path: /opt/code
  commands:
  - cd /opt/code
  - ls -al

volumes:
- name: code
  temp: {}
